create table if not exists workspaces (
  id bigint generated by default as identity primary key,
  name varchar(200) not null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table if not exists pages (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null,
  title varchar(255) not null,
  parent_id bigint null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  constraint fk_pages_workspace foreign key (workspace_id) references workspaces(id),
  constraint fk_pages_parent foreign key (parent_id) references pages(id)
);

create index if not exists idx_pages_workspace_id on pages(workspace_id);
create index if not exists idx_pages_parent_id on pages(parent_id);

create table if not exists blocks (
  id bigint generated by default as identity primary key,
  page_id bigint not null,
  type varchar(50) not null,
  content text not null,
  position_index integer not null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  constraint fk_blocks_page foreign key (page_id) references pages(id) on delete cascade,
  constraint uk_blocks_page_position unique (page_id, position_index)
);

create index if not exists idx_blocks_page_id on blocks(page_id);

insert into workspaces (name)
select 'Default Workspace'
where not exists (select 1 from workspaces);
